version: 2

references:
  dependencies_cache_key: &dependencies_cache_key
    dependencies-cache-{{ checksum "package.json" }}

  restore_dependencies_cache: &restore_dependencies_cache
    restore_cache:
      keys:
        - *dependencies_cache_key
        # fallback to using the latest cache if no exact match is found
        - dependencies-cache-

jobs:
  test:
    docker:
      - image: circleci/node:10.11.0

    working_directory: ~/repo

    steps:
      - checkout
      - *restore_dependencies_cache

      # install any missing dependency
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: *dependencies_cache_key

      - run: yarn ci

  publish:
    docker:
      - image: circleci/node:10.11.0

    working_directory: ~/repo

    steps:
      - checkout
      - *restore_dependencies_cache

      - run: yarn publish

workflows:
  version: 2
  test-and-publish:
    jobs:
      - test
      # - publish:
      #     requires:
      #       - test
      #     filters:
      #       tags:
      #         only: /^v.*/
      #       branches:
      #         only: master
